/* i18n dictionary — EN + PT-BR */

export const STRINGS = {
  en: {
    locale: "en",
    nav: {
      process: "Process",
      services: "Services",
      infra: "Infrastructure",
      estimate: "Estimate",
      about: "About",
      book: "Book a call",
    },
    hero: {
      tag: "now booking June engagements",
      version: "v · 26.q2",
      headline: "Built to survive a million users.",
      headlineItalic: "survive a million users",
      sub: "Whether you're scaling a mature platform or shipping a brand-new vibe-coded app, we make sure it doesn't fall over on launch day.",
      ctaPrimary: "Book a 30-min call",
      ctaSecondary: "See packages",
      availability: "2 of 4 slots open · jun",
    },
    rps: {
      title: "requests / second",
      live: "live · synthetic",
      unit: "req/s",
      peak: "peak",
      p95: "p95 latency",
      err: "error rate",
      scenario: "scenario · checkout-flow_v2.k6.js",
      status: "passing",
    },
    logos: { label: "Built on k6 — trusted by" },
    process: {
      eyebrow: "How it works",
      title: 'Four weeks from "will this hold?" to a launch you can defend in a postmortem.',
      titleItalic: '"will this hold?"',
      steps: [
        { n: "01", title: "Map your traffic",       body: "I dig into your real user flows — checkout, signup, search, the AI calls — and turn them into a realistic k6 test plan. No synthetic nonsense." },
        { n: "02", title: "Stress until it breaks", body: "Custom scenarios ramp from a trickle to a tidal wave. We watch latency, error rate, DB connections, AI provider limits — everything that matters." },
        { n: "03", title: "Find the cracks",        body: "I produce a detailed report: which endpoint dies first, what the root cause is, and the specific fix — index, queue, cache, rewrite, or scale-up." },
        { n: "04", title: "Re-test & ship",         body: "Once you've applied fixes, we run the gauntlet again until your app holds the load you actually need. Then you launch with receipts." },
      ],
    },
    services: {
      eyebrow: "Engagements",
      title: "Three ways to work together — all fixed scope, all yours.",
      titleItalic: "fixed scope",
      price: "Contact for quote",
      pillTop: "Most picked",
      items: [
        {
          tagline: "Fixed scope · 1 week",
          title: "Smoke Audit",
          bullets: [
            "One critical user flow, hammered to failure",
            "Bottleneck identified with k6 + custom probes",
            "Written 8-page report with fixes prioritized",
            "Async-only — no meetings, just answers",
          ],
          cta: "Start an audit",
        },
        {
          tagline: "Most popular · 3–4 weeks",
          title: "Launch-Ready",
          bullets: [
            "Full flow coverage — checkout, auth, search, AI calls",
            "Realistic load profiles modelled from your analytics",
            "Soak tests, spike tests, rate-limit & queue analysis",
            "Two rounds of fix-and-re-test, plus a launch playbook",
          ],
          cta: "Get launch-ready",
        },
        {
          tagline: "Ongoing · monthly",
          title: "Resilience Retainer",
          bullets: [
            "Nightly load tests in your CI, owned and tuned by me",
            "On-call for incidents and pre-launch capacity reviews",
            "Quarterly chaos & failover exercises",
            "Slack channel, monthly capacity report, no surprises",
          ],
          cta: "Talk retainer",
        },
      ],
    },
    infra: {
      eyebrow: "Infrastructure",
      title: "Real iron when you need it, real cloud when you can't.",
      titleItalic: "real cloud when you can't.",
      sub: "Most engagements run on dedicated bare-metal rigs in my lab — fast, predictable, no rate-limited free tiers. When your test needs to outgrow them, we scale into AWS / GCP on your behalf.",
      local: {
        kind: "01 · local",
        label: "On-prem rig",
        value: "1 TB",
        unit: "RAM",
        spec: "dedicated",
        capacity: "≈ 1.2M virtual users",
        note: "For the vast majority of engagements. No queue, no cold start, no metered surprises — the rig is yours for the duration of the test window.",
        bullets: [
          "Dedicated to your test — no noisy neighbours",
          "100 GbE pipe to the public internet",
          "Multi-region egress via wireguard",
        ],
      },
      cloud: {
        kind: "02 · cloud",
        label: "Burst to cloud",
        value: "∞",
        unit: "virtual users",
        spec: "on demand",
        capacity: "client-billed at cost",
        note: "When the local rig isn't enough — launches, big public events, or geo-distributed load — we orchestrate k6 across AWS / GCP regions. You see every line item.",
        bullets: [
          "Multi-region: us, eu, sa, ap",
          "Tear-down within the hour after each run",
          "Cost-pass-through, no infra margin",
        ],
      },
    },
    calc: {
      eyebrow: "Estimate",
      title: "How many users do you need to hold up to?",
      titleItalic: "hold up to?",
      q: "Target monthly active users",
      perMonth: "/ month",
      help: "Drag to set the scale your app should survive on its worst day.",
      recEyebrow: "Recommended engagement",
      peakRps: "Est. peak RPS",
      monthlyReq: "Monthly requests",
      cta: "Get a tailored quote",
      rec: {
        smoke:  { name: "Smoke Audit",          meta: "1 critical flow · 1 week" },
        launch: { name: "Launch-Ready",         meta: "Full flows · 3–4 weeks" },
        retain: { name: "Resilience Retainer",  meta: "Ongoing · monthly" },
      },
    },
    testimonials: {
      eyebrow: "Receipts",
      title: "What founders say after the load test dust settles.",
      titleItalic: "load test dust settles.",
      items: [
        { q: "Henri found three bottlenecks our APM never showed us. We went from falling over at 8k concurrent users to comfortably handling 60k.", name: "Maya Okonkwo", role: "CTO · Voltgrid", initials: "MO" },
        { q: "The app was built end-to-end with AI tooling — Henri treated it with zero judgment and just made it production-grade in three weeks.", name: "Rafael Mendes", role: "Founder · Pillar/AI", initials: "RM" },
        { q: "We hired him a week before a Product Hunt launch. The report alone was worth 10x the fee. We didn't get paged once.", name: "Astrid Lindqvist", role: "Co-founder · Soma", initials: "AL" },
      ],
    },
    about: {
      eyebrow: "About",
      title: "Henri Cavalcante — performance engineer for startups that can't afford a bad launch day.",
      titleItalic: "can't afford a bad launch day.",
      portrait: "[ portrait — drop here ]",
      p1: ["I've spent the last ", "nine years", " breaking systems on purpose — from fintech APIs handling million-dollar transactions to AI products with unpredictable GPU-bound costs. I run ", "BBH", ", a small studio of services for technical founders; this site is the load-testing arm of that practice."],
      p2: "My approach is opinionated and quiet. No 40-page sales decks, no enterprise theater. You get one engineer who reads your code, writes the tests, finds the failures, and hands you a fix list you can actually execute against.",
      p3: "I work with k6 as the backbone — extended with custom probes for Postgres, Redis, BullMQ, edge runtimes, and LLM provider rate limits. The output is always the same: a launch day where nothing surprises you.",
      stats: [
        { num: "92",    lbl: "engagements shipped" },
        { num: "0",     lbl: "launch-day pages*" },
        { num: "~14d",  lbl: "avg. turnaround" },
      ],
      footnote: "* across launches where my fix list was implemented before going live.",
    },
    contact: {
      eyebrow: "Book a call",
      titleA: "30 minutes.",
      titleItalic: "No deck.",
      titleB: "Just your app and the load you're afraid of.",
      lead: "Tell me where you are. I'll reply within one business day with whether I can help, a rough timeline, and a fixed-fee proposal — or a referral if I'm not the right fit.",
      direct: "Direct",
      fields: {
        name: "Name",
        email: "Email",
        stage: "Stage",
        note: "What's worrying you?",
        notePh: "e.g. We're expecting 100k signups in a week and have no idea if the auth flow holds.",
      },
      stages: ["Pre-launch", "Just launched", "Scaling pains", "Big event coming"],
      submit: "Send request →",
      sent: "✓ Sent — talk soon",
      sentMsg: "I'll reply within one business day.",
    },
    footer: {
      tag: "Built in Brazil, deployed worldwide",
    },
  },

  pt: {
    locale: "pt-BR",
    nav: {
      process: "Processo",
      services: "Serviços",
      infra: "Infraestrutura",
      estimate: "Estimativa",
      about: "Sobre",
      book: "Agendar conversa",
    },
    hero: {
      tag: "agendando projetos para junho",
      version: "v · 26.t2",
      headline: "Feito para sustentar um milhão de usuários.",
      headlineItalic: "sustentar um milhão de usuários",
      sub: "Seja escalando uma plataforma madura ou lançando um app recém-vibe-codado, garantimos que ele não vai cair no dia do lançamento.",
      ctaPrimary: "Agendar conversa de 30 min",
      ctaSecondary: "Ver pacotes",
      availability: "2 de 4 vagas abertas · jun",
    },
    rps: {
      title: "requisições / segundo",
      live: "ao vivo · sintético",
      unit: "req/s",
      peak: "pico",
      p95: "latência p95",
      err: "taxa de erro",
      scenario: "cenário · checkout-flow_v2.k6.js",
      status: "aprovado",
    },
    logos: { label: "Feito com k6 — em uso por" },
    process: {
      eyebrow: "Como funciona",
      title: 'Quatro semanas entre "isso vai aguentar?" e um lançamento que você defende em qualquer postmortem.',
      titleItalic: '"isso vai aguentar?"',
      steps: [
        { n: "01", title: "Mapear seu tráfego",   body: "Mergulho nos fluxos reais — checkout, cadastro, busca, chamadas de IA — e transformo tudo em um plano de teste k6 realista. Nada de sintético sem sentido." },
        { n: "02", title: "Forçar até quebrar",   body: "Cenários sob medida que sobem do gotejo a uma tsunami. Acompanhamos latência, taxa de erro, conexões de banco, limites de provedores de IA — tudo o que importa." },
        { n: "03", title: "Achar as rachaduras", body: "Entrego um relatório detalhado: qual endpoint cai primeiro, qual a causa raiz, e o ajuste exato — índice, fila, cache, reescrita ou escala." },
        { n: "04", title: "Retestar e lançar",   body: "Depois dos ajustes aplicados, rodamos a maratona de novo até o app aguentar a carga que você precisa. Aí você lança com provas." },
      ],
    },
    services: {
      eyebrow: "Projetos",
      title: "Três formas de trabalhar comigo — todas com escopo fechado, todas suas.",
      titleItalic: "escopo fechado",
      price: "Sob consulta",
      pillTop: "Mais escolhido",
      items: [
        {
          tagline: "Escopo fechado · 1 semana",
          title: "Auditoria Smoke",
          bullets: [
            "Um fluxo crítico, martelado até falhar",
            "Gargalo identificado com k6 + sondas customizadas",
            "Relatório escrito de 8 páginas com correções priorizadas",
            "Só assíncrono — sem reuniões, só respostas",
          ],
          cta: "Iniciar auditoria",
        },
        {
          tagline: "Mais popular · 3–4 semanas",
          title: "Pronto para Lançar",
          bullets: [
            "Cobertura completa — checkout, auth, busca, chamadas de IA",
            "Perfis de carga realistas modelados a partir do seu analytics",
            "Testes soak, spike, análise de rate-limit e filas",
            "Duas rodadas de ajuste-e-reteste, mais um playbook de lançamento",
          ],
          cta: "Ficar pronto",
        },
        {
          tagline: "Contínuo · mensal",
          title: "Retainer de Resiliência",
          bullets: [
            "Testes de carga noturnos no seu CI, mantidos e afinados por mim",
            "Plantão para incidentes e revisões de capacidade pré-lançamento",
            "Exercícios trimestrais de chaos e failover",
            "Canal no Slack, relatório mensal, sem surpresas",
          ],
          cta: "Conversar sobre retainer",
        },
      ],
    },
    infra: {
      eyebrow: "Infraestrutura",
      title: "Ferro de verdade quando você precisa, nuvem de verdade quando não dá.",
      titleItalic: "nuvem de verdade quando não dá.",
      sub: "A maioria dos projetos roda em servidores bare-metal dedicados no meu laboratório — rápidos, previsíveis, sem free-tier limitado. Quando o teste cresce além disso, escalamos para AWS / GCP em seu nome.",
      local: {
        kind: "01 · local",
        label: "Rig on-prem",
        value: "1 TB",
        unit: "de RAM",
        spec: "dedicado",
        capacity: "≈ 1,2 milhão de usuários virtuais",
        note: "Para a grande maioria dos projetos. Sem fila, sem cold start, sem surpresas medidas — a máquina é sua durante toda a janela do teste.",
        bullets: [
          "Dedicado ao seu teste — sem vizinhos barulhentos",
          "Link de 100 GbE para a internet pública",
          "Saída multi-região via wireguard",
        ],
      },
      cloud: {
        kind: "02 · nuvem",
        label: "Burst pra nuvem",
        value: "∞",
        unit: "usuários virtuais",
        spec: "sob demanda",
        capacity: "cobrado direto do cliente",
        note: "Quando o rig local não dá conta — lançamentos, eventos públicos grandes ou carga geo-distribuída — orquestramos k6 em regiões da AWS / GCP. Você vê cada item da nota.",
        bullets: [
          "Multi-região: us, eu, sa, ap",
          "Tear-down em até uma hora após a rodada",
          "Repasse de custo, sem margem de infra",
        ],
      },
    },
    calc: {
      eyebrow: "Estimativa",
      title: "Para quantos usuários seu app precisa aguentar?",
      titleItalic: "aguentar?",
      q: "Usuários ativos mensais alvo",
      perMonth: "/ mês",
      help: "Arraste para definir a escala que seu app precisa sobreviver no pior dia.",
      recEyebrow: "Projeto recomendado",
      peakRps: "RPS de pico est.",
      monthlyReq: "Requisições por mês",
      cta: "Receber uma proposta sob medida",
      rec: {
        smoke:  { name: "Auditoria Smoke",          meta: "1 fluxo crítico · 1 semana" },
        launch: { name: "Pronto para Lançar",       meta: "Fluxos completos · 3–4 semanas" },
        retain: { name: "Retainer de Resiliência",  meta: "Contínuo · mensal" },
      },
    },
    testimonials: {
      eyebrow: "Provas",
      title: "O que fundadores dizem depois que a poeira do teste de carga assenta.",
      titleItalic: "poeira do teste de carga assenta.",
      items: [
        { q: "O Henri achou três gargalos que nosso APM nunca mostrou. Saímos de cair com 8 mil usuários simultâneos para aguentar 60 mil tranquilo.", name: "Maya Okonkwo", role: "CTO · Voltgrid", initials: "MO" },
        { q: "O app foi construído ponta a ponta com IA — Henri tratou sem julgamento e em três semanas tornou tudo production-grade.", name: "Rafael Mendes", role: "Fundador · Pillar/AI", initials: "RM" },
        { q: "Contratei ele uma semana antes do lançamento no Product Hunt. Só o relatório já valeu dez vezes o investimento. Não tomei um page sequer.", name: "Astrid Lindqvist", role: "Cofundadora · Soma", initials: "AL" },
      ],
    },
    about: {
      eyebrow: "Sobre",
      title: "Henri Cavalcante — engenheiro de performance para startups que não podem ter um dia de lançamento ruim.",
      titleItalic: "não podem ter um dia de lançamento ruim.",
      portrait: "[ retrato — deixe aqui ]",
      p1: ["Passei os últimos ", "nove anos", " quebrando sistemas de propósito — de APIs fintech movimentando transações de milhões de dólares a produtos de IA com custos imprevisíveis em GPU. Toco a ", "BBH", ", um pequeno estúdio de serviços para fundadores técnicos; este site é o braço de testes de carga."],
      p2: "Minha abordagem é opinativa e silenciosa. Nada de decks de 40 páginas, nada de teatro enterprise. Você recebe um engenheiro que lê seu código, escreve os testes, acha as falhas e entrega uma lista de correções que dá para executar.",
      p3: "Trabalho com k6 como base — estendido com sondas customizadas para Postgres, Redis, BullMQ, runtimes edge e limites de provedores LLM. O resultado é sempre o mesmo: um lançamento sem surpresas.",
      stats: [
        { num: "92",    lbl: "projetos entregues" },
        { num: "0",     lbl: "pages no lançamento*" },
        { num: "~14d",  lbl: "tempo médio" },
      ],
      footnote: "* em lançamentos onde minha lista de correções foi implementada antes de subir.",
    },
    contact: {
      eyebrow: "Agendar conversa",
      titleA: "30 minutos.",
      titleItalic: "Sem deck.",
      titleB: "Só o seu app e a carga que te tira o sono.",
      lead: "Me conte onde você está. Respondo em até um dia útil dizendo se posso ajudar, um cronograma aproximado e uma proposta com preço fechado — ou indico alguém se eu não for a pessoa certa.",
      direct: "Direto",
      fields: {
        name: "Nome",
        email: "E-mail",
        stage: "Estágio",
        note: "O que está te preocupando?",
        notePh: "ex.: estamos esperando 100 mil cadastros em uma semana e não fazemos ideia se o fluxo de auth aguenta.",
      },
      stages: ["Pré-lançamento", "Acabou de lançar", "Dores de escala", "Evento grande chegando"],
      submit: "Enviar pedido →",
      sent: "✓ Enviado — até logo",
      sentMsg: "Respondo em até um dia útil.",
    },
    footer: {
      tag: "Construído no Brasil, implantado mundialmente",
    },
  },
};
